### ISSUE TITLE
I can't search all accounts

### ISSUE THREAD

**Issue by Luongzz** [0xCyll/valorant-tracking-bot#2]
The problem is when i use riot id username and account, i see it error "Invalid username and tag. Please provide a valid Valorant username and tag." when i find my friend's account the bot works normally

**Comment by 0xCyll** [comment]
That would make sense as your meant to put in the valorant username and tag not your riot id username

**Comment by Luongzz** [comment]
Oh, ty

**Comment by 0xCyll** [comment]
Your Welcome! If you have any suggestions or ideas for the bot later. Please do let me know!

**Comment by Luongzz** [comment]
![image](https://github.com/0xCyll/valorant-tracking-bot/assets/37655807/1ae16b6a-08ad-4872-ab34-31aa47be6591)
![image](https://github.com/0xCyll/valorant-tracking-bot/assets/37655807/5f745844-f163-4929-8ad8-55340a67c531)
it seems the error persists

**Comment by 0xCyll** [comment]
What region is your valorant account may i ask? because this code is intended for the Europe region

**Comment by Luongzz** [comment]
I live in Asia

**Comment by 0xCyll** [comment]
Okay got it, by the end of tomorrow hopefully i will make changes to include Asia.

**Comment by Luongzz** [comment]
So what should I replace eu with now to find it?

**Comment by 0xCyll** [comment]
replace eu with "ap" if that doesn't work try "kr" , you will know when it works because it will send the last match played.

**Comment by Luongzz** [comment]
> 

both options are not working

**Comment by 0xCyll** [comment]
That is a bit unfortunate, as i am not home at the moment there is not a lot i can do. I am sorry

**Comment by Luongzz** [comment]
> That is a bit unfortunate, as i am not home at the moment there is not a lot i can do. I am sorry

it's okay, take it easy

**Comment by 0xCyll** [comment]
I fixed it and tested your user and it should work.

**Comment by Luongzz** [comment]
![image](https://github.com/0xCyll/valorant-tracking-bot/assets/37655807/1d408231-6a12-4a0a-b0ac-beb558b06c6c)
when i use command /view_tracked_users it shows nothing

**Comment by 0xCyll** [comment]
The unkown interaction suggests the command isnt synced which is very unusal since you are running it, i would reccomend restarting the bot and waiting a bit until you see the bot playing its custom status and then try again as it is what i did and it worked
 also please run setup.py for emojis as you will face the missing "emoji_list.json" error

**Comment by Luongzz** [comment]
so should i run the bot using setup.py or main.py?

**Comment by 0xCyll** [comment]
the main bot using main.py, the setup,py allows character icons to be used as emojis and causes the missing emoji_list.json error you should only run it once and for the server id create a server and give the bot admin rights so it can use the emojis from that server, once the bot is running from setup.py run !download to download the icons and then follow any needed instructions

**Comment by Luongzz** [comment]
oh i got it thanks for the help

**Comment by 0xCyll** [comment]
no worries always here to help!
