### ISSUE TITLE
Buttom Error

### ISSUE THREAD

**Issue by qwer2415wy** [0xCyll/valorant-tracking-bot#3]
Hello there I try to use Buttom of bot, When I click button I got the error
```
"match_id = re.search(r"MatchID • ([\w-]+) •", footer).group(1) if footer else None
AttributeError: 'NoneType' object has no attribute 'group'"
```

**Comment by 0xCyll** [comment]
Did you change any of the code as it can't find the matchID from the embed here

**Comment by 0xCyll** [comment]
Live embed does not seem possible through API, so it will only send after game ends.

**Comment by 0xCyll** [comment]
I just checked it out, and i assume you sign into the app with your riot account allowing live track? I will try to look for a live tracking method soon, but most require you to sign in with your riot account which is something i do not want
