### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by Luongzz** [0xCyll/valorant-tracking-bot#4]
![image](https://github.com/0xCyll/valorant-tracking-bot/assets/37655807/7907a987-9d0b-46d5-a30c-788cebefe121)

**Comment by 0xCyll** [comment]
By default the bots prefix is "!", you have a bot on your server a music bot i'm guessing where their prefix is "!" to simply fix this, change the prefix to something like "::" or ">>" this will fix the issue of these unknown commands.

**Comment by Luongzz** [comment]
> By default the bots prefix is "!", you have a bot on your server a music bot i'm guessing where their prefix is "!" to simply fix this, change the prefix to something like "::" or ">>" this will fix the issue of these unknown commands.

I use the slash command

**Comment by Luongzz** [comment]
> I know but in line 24, there is command_prefix="!", i suggest you change the prefix if you don't want those errors, however the errors shouldn't affect the bot in any shape or form.

ty, i will try
